# Generated by Django 4.0.6 on 2022-07-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleitem',
            old_name='time_table',
            new_name='schedule',
        ),
    ]
